const NOTIFICATION_TYPES = {
  NUEVA_OPORTUNIDAD: "NUEVA_OPORTUNIDAD",
  CAMBIO_ESTATUS: "CAMBIO_ESTATUS",
  CAMBIO_HORARIO: "CAMBIO_HORARIO",
  NUEVO_HORARIO: "NUEVO_HORARIO",
  RECHAZO: "RECHAZO",
  SOCIO_APLICA: "SOCIO_APLICA",
};

export default NOTIFICATION_TYPES;
