const NOTIFICATION_TYPES = {
  NUEVA_OPORTUNIDAD: "NUEVA_OPORTUNIDAD",
  OPORTUNIDAD_ELIMINADA: "OPORTUNIDAD_ELIMINADA",
  CAMBIO_ESTATUS: "CAMBIO_ESTATUS",
  CAMBIO_HORARIO: "CAMBIO_HORARIO",
  NUEVO_HORARIO: "NUEVO_HORARIO",
  PARTICIPACION_RECHAZADA: "PARTICIPACION_RECHAZADA",
  PARTICIPACION_GANADOR: "PARTICIPACION_GANADOR",
  NUEVA_PARTICIPACION: "NUEVA_PARTICIPACION",
  NUEVO_EVENTO: "NUEVO_EVENTO",
  CAMBIO_EVENTO: "CAMBIO_EVENTO",
  EVENTO_ELIMINADO: "EVENTO_ELIMINADO",
  OPORTUNIDAD_CERRADA_NO_PARTICIPACIONES: "OPORTUNIDAD_CERRADA_NO_PARTICIPACIONES",
  PARTICIPACION_NUEVO_ARCHIVO: "PARTICIPACION_NUEVO_ARCHIVO",
};

export default NOTIFICATION_TYPES;
