const notificationTypes = {};

notificationTypes.NUEVA_OPORTUNIDAD = "NUEVA_OPORTUNIDAD";
notificationTypes.OPORTUNIDAD_ELIMINADA = "OPORTUNIDAD_ELIMINADA";
notificationTypes.NUEVA_PARTICIPACION = "NUEVA_PARTICIPACION";
notificationTypes.NUEVO_EVENTO = "NUEVO_EVENTO";
notificationTypes.CAMBIO_EVENTO = "CAMBIO_EVENTO";
notificationTypes.CAMBIO_ESTATUS = "CAMBIO_ESTATUS";
notificationTypes.CAMBIO_ESTATUS_PARTICIPACION = "CAMBIO_ESTATUS_PARTICIPACION";
notificationTypes.PARTICIPACION_RECHAZADA = "PARTICIPACION_RECHAZADA";
notificationTypes.PARTICIPACION_GANADOR = "PARTICIPACION_GANADOR";
notificationTypes.EVENTO_ELIMINADO = "EVENTO_ELIMINADO";
notificationTypes.OPORTUNIDAD_CERRADA_NO_PARTICIPACIONES = "OPORTUNIDAD_CERRADA_NO_PARTICIPACIONES";

module.exports = notificationTypes;
